name: CI/CD Pipeline EC2 AWS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/poll-app:latest \
                       -t ${{ secrets.DOCKER_USERNAME }}/poll-app:${{ github.sha }} .

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/poll-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/poll-app:${{ github.sha }}

      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            docker stop poll-app || true
            docker rm poll-app || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/poll-app:latest
            docker run -d -p 8000:8000 --name poll-app ${{ secrets.DOCKER_USERNAME }}/poll-app:latest
